import { library } from "@fortawesome/fontawesome-svg-core";
import {
    faUser,
    faCog,
    faPlus,
    faPenNib,
    faPenToSquare,
    faGear,
    faSearch,
    faBell,
    faEnvelope,
    faPaperPlane,
    faArrowRightLong,
    faArrowLeftLong,
    faEllipsisVertical,
    faMicrophone,
    faMicrophoneSlash,
    faEllipsis,
    faVideo,
    faPhone,
    faVideoSlash,
    faComments,
    faReply,
    faFaceSmile,
    faXmark,

} from "@fortawesome/free-solid-svg-icons";

library.add(
    faUser,
    faCog,
    faPlus,
    faPenNib,
    faPenToSquare,
    faGear,
    faSearch,
    faBell,
    faEnvelope,
    faPaperPlane,
    faArrowRightLong,
    faArrowLeftLong,
    faEllipsisVertical,
    faMicrophone,
    faMicrophoneSlash,
    faEllipsis,
    faVideo,
    faPhone,
    faVideoSlash,
    faComments,
    faReply,
    faFaceSmile,
    faXmark,
);
